name: "check"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

jobs:
  run:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v3"
      - run: "make check"
